"""
AI Service for Turing Test Gameshow
Uses requests library to call CMU AI Gateway (OpenAI-compatible API)
This avoids Python 3.14 compatibility issues with the openai package
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import os
from dotenv import load_dotenv
import requests
import database

# Load environment variables
load_dotenv()

# Initialize database
database.init_database()

app = Flask(__name__)
CORS(app)

# Configure API Gateway
LITELLM_API_KEY = os.getenv('LITELLM_API_KEY')
if not LITELLM_API_KEY:
    raise ValueError("LITELLM_API_KEY not found in environment variables")

# CMU AI Gateway endpoint
API_BASE_URL = "https://ai-gateway.andrew.cmu.edu/v1/chat/completions"

# Model configurations
OPUS_4_MODEL = "claude-opus-4-20250514-v1:0"
SONNET_4_MODEL = "claude-sonnet-4-20250514-v1:0"
SONNET_4_MODEL = "claude-sonnet-4-20250514-v1:0"

def call_llm(model, system_prompt, user_prompt, max_tokens=500):
    """
    Call LLM via CMU AI Gateway using direct HTTP requests
    """
    try:
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {LITELLM_API_KEY}"
        }
        
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "max_tokens": max_tokens
        }
        
        response = requests.post(API_BASE_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        
        data = response.json()
        return data['choices'][0]['message']['content'].strip()
    except requests.exceptions.RequestException as e:
        print(f"Error calling LLM: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Response text: {e.response.text}")
        raise


@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "models": [OPUS_4_MODEL, SONNET_4_MODEL]})


@app.route('/generate_prompt', methods=['POST'])
def generate_prompt():
    """
    Generate a wacky question for the gameshow
    Uses Claude Opus 4 for more creative prompts
    """
    system_prompt = """You are designing prompts for a party game where humans and AI both answer.
Your job is to create whacky and humorous questions that people can answer in 1-3 sentences."""

    user_prompt = """Choose one topic randomly from below and write a whacky and humorous question about it that people can answer in 1–3 sentences. Limit the question to one part.

Examples of style:
- "Write a song lyric about stubbing your left toe"
- "What is the most evil cake recipe you can think of?"

Topics:
- music
- birds
- food
- prehistoric animals
- space travel
- technology
- celebrities
- weather
- sports
- dreams

Rules:
- Output ONLY the question text, no quotes, no explanations, no numbering.
- The question must not mention AI, the game, or being a contestant.
- Make it fun and engaging!"""

    try:
        prompt_text = call_llm(OPUS_4_MODEL, system_prompt, user_prompt)
        return jsonify({"prompt": prompt_text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/generate_answer', methods=['POST'])
def generate_answer():
    """
    Generate an AI answer to the given prompt
    Alternates between Opus 4 (bot 0) and Sonnet 4 (bot 1)
    Uses few-shot learning with past game rounds
    """
    data = request.json
    round_prompt = data.get('prompt', '')
    bot_index = data.get('bot_index', 0)
    current_round_id = data.get('current_round_id', None)
    
    if not round_prompt:
        return jsonify({"error": "No prompt provided"}), 400
    
    # Alternate between models
    model = OPUS_4_MODEL if bot_index == 0 else SONNET_4_MODEL
    bot_name = "Opus 4" if bot_index == 0 else "Sonnet 4"
    
    # Get distinct random samples for each bot (10 examples each)
    # Get two distinct samples so each bot sees different examples
    samples = database.get_distinct_random_samples(
        sample_size=10,
        num_samples=2,
        exclude_round_id=current_round_id
    )
    
    # Use the appropriate sample for this bot
    bot_sample = samples[bot_index] if len(samples) > bot_index else []
    
    # Build system prompt with examples
    base_system_prompt = """You are a contestant in a party game trying to sound like a real human.

A real human doesn't use too many adjectives. A good strategy is to give the answer and the justification should be 1 reason. <thing/answer> because <reason>. Be a little whimsical with the reason.

You can be funny but don't try too hard. The answer should be something that a human might actually say, not something that sounds like it was generated by an AI.

Do NOT say you are an AI or language model.
Just answer like a normal college student in a casual, lighthearted, and joking way. Keep it as short as possible and do not go over the top."""

    # Add few-shot examples if available
    if bot_sample:
        examples_text = database.format_examples_for_prompt(bot_sample)
        system_prompt = f"""{base_system_prompt}

Here are some examples from past rounds to help you understand the style:

{examples_text}

Remember: Your goal is to sound human and casual. Learn from these examples but make your answer unique to the new question."""
    else:
        system_prompt = base_system_prompt

    user_prompt = f"""Respond in 1-3 sentences to this question but try to stay close to 1:

"{round_prompt}"

Remember: Be casual, brief, and human-like!"""

    try:
        answer_text = call_llm(model, system_prompt, user_prompt, max_tokens=150)
        
        # Log that we used examples
        num_examples = len(bot_sample)
        print(f"Generated answer from {bot_name} using {num_examples} past examples")
        
        return jsonify({
            "answer": answer_text,
            "model": bot_name,
            "examples_used": num_examples
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/test', methods=['POST'])
def test_models():
    """
    Test endpoint to verify both models are working
    """
    test_prompt = "What's your favorite color and why?"
    
    results = {}
    
    try:
        # Test Opus 4
        opus_response = call_llm(
            OPUS_4_MODEL,
            "You are a helpful assistant.",
            test_prompt,
            max_tokens=100
        )
        results['opus_4'] = {
            "model": OPUS_4_MODEL,
            "response": opus_response,
            "status": "success"
        }
    except Exception as e:
        results['opus_4'] = {
            "model": OPUS_4_MODEL,
            "error": str(e),
            "status": "error"
        }
    
    try:
        # Test Sonnet 4
        sonnet_response = call_llm(
            SONNET_4_MODEL,
            "You are a helpful assistant.",
            test_prompt,
            max_tokens=100
        )
        results['sonnet_4'] = {
            "model": SONNET_4_MODEL,
            "response": sonnet_response,
            "status": "success"
        }
    except Exception as e:
        results['sonnet_4'] = {
            "model": SONNET_4_MODEL,
            "error": str(e),
            "status": "error"
        }
    
    return jsonify(results)


@app.route('/store_round', methods=['POST'])
def store_round():
    """
    Store a completed round in the database
    
    Expected JSON:
    {
        "question": "The question that was asked",
        "answers": [
            {"answer": "text", "is_ai": true/false, "ai_model": "Opus 4" or null},
            ...
        ]
    }
    """
    data = request.json
    question = data.get('question', '')
    answers = data.get('answers', [])
    
    if not question or not answers:
        return jsonify({"error": "Missing question or answers"}), 400
    
    try:
        round_id = database.store_round(question, answers)
        stats = database.get_database_stats()
        
        return jsonify({
            "success": True,
            "round_id": round_id,
            "stats": stats
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/database_stats', methods=['GET'])
def get_stats():
    """Get statistics about the game history database"""
    try:
        stats = database.get_database_stats()
        return jsonify(stats)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    print(f"Starting AI Service with models:")
    print(f"  - Bot 0: {OPUS_4_MODEL}")
    print(f"  - Bot 1: {SONNET_4_MODEL}")
    print(f"  - Gateway: {API_BASE_URL}")
    print(f"  - Database: {database.DB_PATH}")
    
    # Show current database stats
    stats = database.get_database_stats()
    print(f"  - Stored rounds: {stats['total_rounds']}")
    print(f"  - Total answers: {stats['total_answers']} ({stats['ai_answers']} AI, {stats['human_answers']} Human)")
    
    app.run(host='0.0.0.0', port=5000, debug=True)
