"""
AI Service for Gameshow
Handles AI generation using LiteLLM with Claude Opus 4 and Sonnet 4
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import openai
import os
import random

app = Flask(__name__)
CORS(app)

# Configuration
LITELLM_API_KEY = os.environ.get('LITELLM_API_KEY', '')
LITELLM_BASE_URL = "https://ai-gateway.andrew.cmu.edu/"

# Initialize OpenAI client with LiteLLM (lazily to avoid initialization errors)
llm = None

def get_llm_client():
    """Get or create the LiteLLM client"""
    global llm
    if llm is None:
        llm = openai.OpenAI(
            api_key=LITELLM_API_KEY,
            base_url=LITELLM_BASE_URL,
            max_retries=2,
            timeout=30.0
        )
    return llm

# AI Models for the two bots
BOT_MODELS = {
    'bot-0': 'claude-opus-4-20250514-v1:0',      # Opus 4
    'bot-1': 'claude-sonnet-4-20250514-v1:0'     # Sonnet 4
}

def get_model_for_bot(bot_id):
    """Determine which model to use based on bot ID"""
    # Extract bot number from ID (e.g., "bot-ABC123-0" -> 0)
    if 'bot' in bot_id:
        parts = bot_id.split('-')
        if len(parts) >= 3 and parts[-1].isdigit():
            bot_num = int(parts[-1])
            return BOT_MODELS.get(f'bot-{bot_num}', BOT_MODELS['bot-0'])
    return BOT_MODELS['bot-0']


@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "service": "ai-gameshow"})


@app.route('/generate-prompt', methods=['POST'])
def generate_prompt():
    """
    Generate a whacky question prompt for the game
    Uses Opus 4 for creative question generation
    """
    try:
        prompt_for_model = """
You are designing prompts for a party game where humans and AI both answer.
Choose one topic randomly from below and write a whacky and humorous question about it that people can answer in 1–3 sentences. Limit the question to one part.

Examples of style:
- "Write a song lyric about stubbing your left toe"
- "What is the most evil cake recipe you can think of?"

Topics:
music,
birds,
food,
prehistoric animals,
Space travel

Rules:
- Output ONLY the question text, no quotes, no explanations, no numbering.
- The question must not mention AI, the game, or being a contestant.
""".strip()

        response = get_llm_client().chat.completions.create(
            model='claude-opus-4-20250514-v1:0',  # Use Opus 4 for creative prompts
            messages=[
                {"role": "user", "content": prompt_for_model}
            ],
            temperature=0.9,  # Higher temperature for more creativity
            max_tokens=150
        )

        question = response.choices[0].message.content.strip()
        # Remove quotes if the model added them
        question = question.strip('"').strip("'")
        
        return jsonify({
            "success": True,
            "prompt": question
        })

    except Exception as e:
        print(f"Error generating prompt: {e}")
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500


@app.route('/generate-answer', methods=['POST'])
def generate_answer():
    """
    Generate an AI answer to the round prompt
    Uses the appropriate model based on bot_id
    """
    try:
        data = request.json
        round_prompt = data.get('prompt', '')
        bot_id = data.get('bot_id', 'bot-0')

        if not round_prompt:
            return jsonify({
                "success": False,
                "error": "No prompt provided"
            }), 400

        # Select model based on bot ID
        model = get_model_for_bot(bot_id)
        
        full_prompt = f"""
You are a contestant in a party game trying to sound like a real human.

A real human doesn't use too many adjectives. A good strategy is to give the answer and the justification should be 1 reason. <thing/answer> because <reason>. Be a little whimsical with the reason.
You can be funny but don't try too hard. The answer should be something that a human might actually say, not something that sounds like it was generated by an AI.
Also don't be cringe

Respond in 1-3 sentences to this question but try to stay close to 1:

"{round_prompt}"

Do NOT say you are an AI or language model.
Just answer like a normal college student in a casual, lighthearted, and joking way. Keep it as short as possible and do not go over the top.
""".strip()

        response = get_llm_client().chat.completions.create(
            model=model,
            messages=[
                {"role": "user", "content": full_prompt}
            ],
            temperature=0.8,
            max_tokens=200
        )

        answer_text = response.choices[0].message.content.strip()
        
        return jsonify({
            "success": True,
            "answer": answer_text,
            "model_used": model
        })

    except Exception as e:
        print(f"Error generating answer: {e}")
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500


@app.route('/generate-batch-answers', methods=['POST'])
def generate_batch_answers():
    """
    Generate answers for multiple bots at once
    """
    try:
        data = request.json
        round_prompt = data.get('prompt', '')
        bot_ids = data.get('bot_ids', [])

        if not round_prompt or not bot_ids:
            return jsonify({
                "success": False,
                "error": "Missing prompt or bot_ids"
            }), 400

        answers = []
        for bot_id in bot_ids:
            model = get_model_for_bot(bot_id)
            
            full_prompt = f"""
You are a contestant in a party game trying to sound like a real human.

A real human doesn't use too many adjectives. A good strategy is to give the answer and the justification should be 1 reason. <thing/answer> because <reason>. Be a little whimsical with the reason.
You can be funny but don't try too hard. The answer should be something that a human might actually say, not something that sounds like it was generated by an AI.

Respond in 1-3 sentences to this question but try to stay close to 1:

"{round_prompt}"

Do NOT say you are an AI or language model.
Just answer like a normal college student in a casual, lighthearted, and joking way. Keep it as short as possible and do not go over the top.
""".strip()

            try:
                response = get_llm_client().chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "user", "content": full_prompt}
                    ],
                    temperature=0.8,
                    max_tokens=200
                )

                answer_text = response.choices[0].message.content.strip()
                answers.append({
                    "bot_id": bot_id,
                    "answer": answer_text,
                    "model_used": model,
                    "success": True
                })
            except Exception as bot_error:
                print(f"Error for bot {bot_id}: {bot_error}")
                answers.append({
                    "bot_id": bot_id,
                    "error": str(bot_error),
                    "success": False
                })

        return jsonify({
            "success": True,
            "answers": answers
        })

    except Exception as e:
        print(f"Error in batch generation: {e}")
        return jsonify({
            "success": False,
            "error": str(e)
        }), 500


if __name__ == '__main__':
    if not LITELLM_API_KEY:
        print("WARNING: LITELLM_API_KEY environment variable not set!")
        print("Please set it before running: export LITELLM_API_KEY='your-key-here'")
    
    print("Starting AI Service...")
    print(f"Bot 0 will use: {BOT_MODELS['bot-0']}")
    print(f"Bot 1 will use: {BOT_MODELS['bot-1']}")
    app.run(host='0.0.0.0', port=5000, debug=True)
