"""
AI Service for Turing Test Gameshow
Uses requests library to call CMU AI Gateway (OpenAI-compatible API)
This avoids Python 3.14 compatibility issues with the openai package
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import os
from dotenv import load_dotenv
import requests

# Load environment variables
load_dotenv()

app = Flask(__name__)
CORS(app)

# Configure API Gateway
LITELLM_API_KEY = os.getenv('LITELLM_API_KEY')
if not LITELLM_API_KEY:
    raise ValueError("LITELLM_API_KEY not found in environment variables")

# CMU AI Gateway endpoint
API_BASE_URL = "https://ai-gateway.andrew.cmu.edu/v1/chat/completions"

# Model configurations
OPUS_4_MODEL = "claude-opus-4-20250514-v1:0"
SONNET_4_MODEL = "claude-sonnet-4-20250514-v1:0"

def call_llm(model, system_prompt, user_prompt, max_tokens=500):
    """
    Call LLM via CMU AI Gateway using direct HTTP requests
    """
    try:
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {LITELLM_API_KEY}"
        }
        
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "max_tokens": max_tokens
        }
        
        response = requests.post(API_BASE_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        
        data = response.json()
        return data['choices'][0]['message']['content'].strip()
    except requests.exceptions.RequestException as e:
        print(f"Error calling LLM: {e}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Response text: {e.response.text}")
        raise


@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "models": [OPUS_4_MODEL, SONNET_4_MODEL]})


@app.route('/generate_prompt', methods=['POST'])
def generate_prompt():
    """
    Generate a wacky question for the gameshow
    Uses Claude Opus 4 for more creative prompts
    """
    system_prompt = """You are designing prompts for a party game where humans and AI both answer.
Your job is to create whacky and humorous questions that people can answer in 1-3 sentences."""

    user_prompt = """Choose one topic randomly from below and write a whacky and humorous question about it that people can answer in 1–3 sentences. Limit the question to one part.

Examples of style:
- "Write a song lyric about stubbing your left toe"
- "What is the most evil cake recipe you can think of?"

Topics:
- music
- birds
- food
- prehistoric animals
- space travel
- technology
- celebrities
- weather
- sports
- dreams

Rules:
- Output ONLY the question text, no quotes, no explanations, no numbering.
- The question must not mention AI, the game, or being a contestant.
- Make it fun and engaging!"""

    try:
        prompt_text = call_llm(OPUS_4_MODEL, system_prompt, user_prompt)
        return jsonify({"prompt": prompt_text})
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/generate_answer', methods=['POST'])
def generate_answer():
    """
    Generate an AI answer to the given prompt
    Alternates between Opus 4 (bot 0) and Sonnet 4 (bot 1)
    """
    data = request.json
    round_prompt = data.get('prompt', '')
    bot_index = data.get('bot_index', 0)
    
    if not round_prompt:
        return jsonify({"error": "No prompt provided"}), 400
    
    # Alternate between models
    model = OPUS_4_MODEL if bot_index == 0 else SONNET_4_MODEL
    bot_name = "Opus 4" if bot_index == 0 else "Sonnet 4"
    
    system_prompt = """You are a contestant in a party game trying to sound like a real human.

A real human doesn't use too many adjectives. A good strategy is to give the answer and the justification should be 1 reason. <thing/answer> because <reason>. Be a little whimsical with the reason.

You can be funny but don't try too hard. The answer should be something that a human might actually say, not something that sounds like it was generated by an AI.

Do NOT say you are an AI or language model.
Just answer like a normal college student in a casual, lighthearted, and joking way. Keep it as short as possible and do not go over the top."""

    user_prompt = f"""Respond in 1-3 sentences to this question but try to stay close to 1:

"{round_prompt}"

Remember: Be casual, brief, and human-like!"""

    try:
        answer_text = call_llm(model, system_prompt, user_prompt, max_tokens=150)
        return jsonify({
            "answer": answer_text,
            "model": bot_name
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/test', methods=['POST'])
def test_models():
    """
    Test endpoint to verify both models are working
    """
    test_prompt = "What's your favorite color and why?"
    
    results = {}
    
    try:
        # Test Opus 4
        opus_response = call_llm(
            OPUS_4_MODEL,
            "You are a helpful assistant.",
            test_prompt,
            max_tokens=100
        )
        results['opus_4'] = {
            "model": OPUS_4_MODEL,
            "response": opus_response,
            "status": "success"
        }
    except Exception as e:
        results['opus_4'] = {
            "model": OPUS_4_MODEL,
            "error": str(e),
            "status": "error"
        }
    
    try:
        # Test Sonnet 4
        sonnet_response = call_llm(
            SONNET_4_MODEL,
            "You are a helpful assistant.",
            test_prompt,
            max_tokens=100
        )
        results['sonnet_4'] = {
            "model": SONNET_4_MODEL,
            "response": sonnet_response,
            "status": "success"
        }
    except Exception as e:
        results['sonnet_4'] = {
            "model": SONNET_4_MODEL,
            "error": str(e),
            "status": "error"
        }
    
    return jsonify(results)


if __name__ == '__main__':
    print(f"Starting AI Service with models:")
    print(f"  - Bot 0: {OPUS_4_MODEL}")
    print(f"  - Bot 1: {SONNET_4_MODEL}")
    print(f"  - Gateway: {API_BASE_URL}")
    app.run(host='0.0.0.0', port=5000, debug=True)
